DELIMITER $$

USE `restuarant`$$

DROP FUNCTION IF EXISTS `FN_IS_SEAT_AVAILABLE`$$

CREATE DEFINER=`root`@`localhost` FUNCTION `FN_IS_SEAT_AVAILABLE`(i_seat_no INT) RETURNS TINYINT(1)
BEGIN
RETURN EXISTS(SELECT STATUS FROM seat_configuration WHERE ID=i_seat_no AND STATUS=0);
END$$

DELIMITER ;