DELIMITER $$

USE `restuarant`$$

DROP FUNCTION IF EXISTS `FN_CHECK_ALL_SEAT_FILLED`$$

CREATE DEFINER=`root`@`localhost` FUNCTION `FN_CHECK_ALL_SEAT_FILLED`() RETURNS TINYINT(1)
BEGIN
RETURN (SELECT((SELECT COUNT(STATUS)FROM seat_configuration WHERE STATUS=1)<(SELECT COUNT(*) FROM seat_configuration)));
END$$

DELIMITER ;