DELIMITER $$

USE `restuarant`$$

DROP FUNCTION IF EXISTS `FN_VALIDATE_FOOD_ITEM`$$

CREATE DEFINER=`root`@`localhost` FUNCTION `FN_VALIDATE_FOOD_ITEM`(i_food_name VARCHAR(30)) RETURNS TINYINT(1)
BEGIN
RETURN (EXISTS(SELECT ID FROM food_item WHERE NAME=i_food_name));
END$$

DELIMITER ;