                                                                                                                                            

/*Table structure for order_food_details*/ 

CREATE TABLE `order_food_details` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                      `ID` int(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                      `ORDER_ID` int(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                      `ORDER_TIMESTAMP` timestamp NULL DEFAULT CURRENT_TIMESTAMP,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                      `FOOD_ID` int(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                      `FOOD_COUNT` int(11) DEFAULT '0',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                      `ORDER_STATUS` varchar(30) DEFAULT 'ORDER SUCCESS',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                      PRIMARY KEY (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                      KEY `FK3` (`FOOD_ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                      KEY `OR_FK` (`ORDER_ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                      CONSTRAINT `OR_FK` FOREIGN KEY (`ORDER_ID`) REFERENCES `order_details` (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                      CONSTRAINT `FK3` FOREIGN KEY (`FOOD_ID`) REFERENCES `food_item` (`ID`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                    )




                                                                                                                                                                                                                                                                                                                                                                                  