/*Table structure for schedule_food_relation*/

CREATE TABLE `schedule_food_relation` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                          `ID` int(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                          `SCHEDULE_ID` int(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                          `FOOD_ID` int(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                          `FOOD_COUNT` int(11) DEFAULT NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                          PRIMARY KEY (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                          UNIQUE KEY `SCHEDULE_ID` (`SCHEDULE_ID`,`FOOD_ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                          KEY `FI_FK` (`FOOD_ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                          CONSTRAINT `SI_FK` FOREIGN KEY (`SCHEDULE_ID`) REFERENCES `seed_schedule` (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                  
                          CONSTRAINT `FI_FK` FOREIGN KEY (`FOOD_ID`) REFERENCES `food_item` (`ID`)                                                                                                                                                                                                                                                                                                                                                                                                                                           
                        ) 

/*Table values for schedule_food_relation*/

INSERT INTO schedule_food_map VALUES(1,1,100),(2,1,100),(3,1,100),(4,1,100),(5,1,100),
				    (6,1,100),(7,1,100),(8,2,75),(9,2,75),(10,2,75),
				    (6,3,200),(7,3,200),(11,3,200),(12,4,100),(13,4,100),
			            (14,4,100)                                                                                                                                                                                                                                                                                                                                                                                                 
