/*Table structure for schedule_food_map*/

CREATE TABLE `schedule_food_map` (                                                                                                                                                                                                                                                                                                                                                                                                       
                     `FOOD_ID` int(11) NOT NULL DEFAULT '0',                                                                                                                                                                                                                                                                                                                                                                                                
                     `SCHEDULE_ID` int(11) NOT NULL DEFAULT '0',                                                                                                                                                                                                                                                                                                                                                                                            
                     `FOOD_COUNT` int(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                     
                     PRIMARY KEY (`FOOD_ID`,`SCHEDULE_ID`),                                                                                                                                                                                                                                                                                                                                                                                                 
                     KEY `FK2` (`SCHEDULE_ID`),                                                                                                                                                                                                                                                                                                                                                                                                             
                     CONSTRAINT `FK1` FOREIGN KEY (`FOOD_ID`) REFERENCES `food_item` (`ID`),                                                                                                                                                                                                                                                                                                                                                                
                     CONSTRAINT `FK2` FOREIGN KEY (`SCHEDULE_ID`) REFERENCES `seed_schedule` (`ID`)                                                                                                                                                                                                                                                                                                                                                         
                   ) 

/*Table values for schedule_food_map*/

INSERT INTO schedule_food_map VALUES(1,1,100),(2,1,100),(3,1,100),(4,1,100),(5,1,100),
				    (6,1,100),(7,1,100),(8,2,75),(9,2,75),(10,2,75),
				    (6,3,200),(7,3,200),(11,3,200),(12,4,100),(13,4,100),
			            (14,4,100)                                                                                                                                                                                                                                                                                                                                                                                                 
