                                                                                                                                            

/*Table structure for transaction_details*/ 

CREATE TABLE `transaction_details` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                       `ID` int(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                       `ORDER_ID` int(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                       `DATE_OF_ORDER` date DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                       `TIME_OF_ORDER` time DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                       `SCHEDULE_ID` int(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                       `FOOD_ID` int(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                       `FOOD_COUNT` int(11) DEFAULT '0',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                       `COST` int(11) DEFAULT '0',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                       `BILL_STATUS` varchar(30) DEFAULT '''Not paid''',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                       PRIMARY KEY (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                       KEY `FK3` (`FOOD_ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                       KEY `FK4` (`SCHEDULE_ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                       CONSTRAINT `FK3` FOREIGN KEY (`FOOD_ID`) REFERENCES `food_item` (`ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                       CONSTRAINT `FK4` FOREIGN KEY (`SCHEDULE_ID`) REFERENCES `seed_schedule` (`ID`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                     )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                





                                                                                                                                                                                                                                                                                                                                                                                  