DELIMITER $$

ALTER DEFINER=`root`@`localhost` EVENT `clean_order` ON SCHEDULE EVERY 1 DAY STARTS '2016-12-22 00:00:01' ON COMPLETION NOT PRESERVE ENABLE DO BEGIN
	    TRUNCATE TABLE order_status;
	END$$

DELIMITER ;